char_palette = {
    'player': '@',
    'npc': '@',
    'quadraped': 'm',
    'avial': 'w',
    'horror': ['¿', '&', 'z', 'q', 'g'],
    'spell': '*',
    'spell_trail': '~',
    'floor': '.',
    'grass': {
        'random': ['`', '"', '\'']
    },
    'lantern': 'ύ',
    'wall': '#',
    'door': ['█','∏'],
    'window': ['■', '□'],
    'ladder': 'Ξ',
    'chair': 'π',
    'table': 'T',
    'candle': 'î',
    'mirror': 'Õ',
    'necklace': 'ŏ',
    'machine_in': ['→','↑','←','↓'],
    'machine_out': ['→','↑','←','↓'],
    'machine_in_out': ['⇄','⇅','⇄','⇅'],
    'money': ['s','S','$'],
    'water': '~',
    'test_tube': '|',
    'beaker': 'U',
    'flask': 'Δ',
    'retort_stand': '7',
    'wand': '/',
    'scroll': '§'
}